name: Run Jobs Selectively

on:
  workflow_dispatch:
    branches: [ "main" ]
    inputs:
      jobs_to_run:
        description: 'Jobs to run'
        required: true
        options: [ 'run_all', 'smoke', 'integration', 'acceptance', 'prod']

jobs:

  smoke:
    name: Smoke job
    runs-on: [ubuntu-latest]
    
    steps:
     - run: echo "We ran the Smoke job"

  integration:
    name: Integration job
    runs-on: [ubuntu-latest]
    needs: [smoke]
    if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.jobs_to_run == 'run_all' || github.event.inputs.jobs_to_run == 'integration') }} 
    
    steps:
     - run: echo "We ran the Integration job"

  acceptance:
    name: Acceptance job
    runs-on: [ubuntu-latest]
    needs: [integration]
    if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.jobs_to_run == 'run_all' || github.event.inputs.jobs_to_run == 'acceptance') }} 
    
    steps:
     - run: echo "We ran the Acceptance job"
  
  prod:
    name: Prod job
    runs-on: [ubuntu-latest]
    needs: [acceptance]
    if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.jobs_to_run == 'run_all' || github.event.inputs.jobs_to_run == 'prod') }} 
    
    steps:
     - run: echo "We ran the Prod job"